[env:teensy41]
platform = teensy
board = teensy41
framework = arduino
monitor_speed = 115200

lib_deps =
  https://github.com/ssilverman/QNEthernet.git
  https://github.com/LoupVaillant/Monocypher.git#4.0.3

build_flags =
  -DTS_TEENSY41_M0
  -DTS_TEENSY41_M1
